import argparse
import sys
from pathlib import Path
from v2m.core.preprocessor import Preprocessor
from v2m.core.reconstructor import Reconstructor
from v2m.core.exporter import Exporter
from v2m.utils.logger import setup_logger

logger = setup_logger(__name__)

def main():
    parser = argparse.ArgumentParser(description="V2M: Video to Mesh Industrial Pipeline")
    parser.add_argument("--video", type=str, required=True, help="Path to input video file")
    parser.add_argument("--output_dir", type=str, required=True, help="Directory to save the outputs")
    
    args = parser.parse_args()
    
    video_path = args.video
    base_output_dir = Path(args.output_dir)
    
    processed_data_dir = base_output_dir / "processed_data"
    training_output_dir = base_output_dir / "training"
    mesh_output_path = base_output_dir / "mesh" / "model.obj"
    
    logger.info("=== Starting V2M Pipeline ===")
    
    # 1. Preprocess
    preprocessor = Preprocessor(str(processed_data_dir))
    if not preprocessor.process_video(video_path):
        logger.error("Pipeline failed at preprocessing stage.")
        sys.exit(1)
        
    # 2. Reconstruct
    reconstructor = Reconstructor(str(processed_data_dir), str(training_output_dir))
    if not reconstructor.train(method="splatfacto"):
        logger.error("Pipeline failed at reconstruction stage.")
        sys.exit(1)
        
    # 3. Export
    # Need to find the config.yml generated by training
    # For nerfstudio, it's usually inside the training_output_dir under the project name
    # We will search for config.yml
    config_files = list(training_output_dir.rglob("config.yml"))
    if not config_files:
        logger.error("Could not find config.yml after training.")
        sys.exit(1)
        
    config_path = config_files[0]
    exporter = Exporter(str(config_path), str(mesh_output_path))
    if not exporter.export_mesh():
        logger.error("Pipeline failed at export stage.")
        sys.exit(1)
        
    logger.info(f"=== V2M Pipeline Completed Successfully! ===")
    logger.info(f"Mesh generated at: {mesh_output_path}")

if __name__ == "__main__":
    main()
